### PR TITLE
[RFC][UN-9281] Add to-money helper

### PR DESCRIPTION
**Pull request by AndreJoaquim**
https://uniplaces.atlassian.net/browse/UN-9281

This was done by @asantos00 for the spa-checkout-frontend. I only migrated it to here and also created an util. Thanks @asantos00, good job!

### CODE REVIEW

**Review by mmelo — APPROVED** [review]
👍

**Review by asantos00 — APPROVED** [review]
GJ 👍

**Comment by asantos00** [comment]
Wait, why would you create an util if you can import the helper directly?

**Comment by AndreJoaquim** [comment]
@asantos00 Modularity and best practices

**Pull request merged**
